apiVersion: v1
kind: Secret
metadata:
  namespace: wordpress
  name: digitalocean
type: kubernetes.io/digitalocean-volume
data:
  token: 8d885cdc892c2fabe7354f6e5f45de90d950e37f7381b358ef01aa8f077dfdb3
  region: sgp1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: wordpress
  name: nfs
spec:
  capacity:
    storage: 20Gi
  accessModes:
    #- ReadWriteOnce
    #- ReadOnlyMany
    - ReadWriteMany
  nfs:
    server: 159.65.132.34
    # Exported path of your NFS server
    path: "/mnt/vol_master"
  persistentVolumeReclaimPolicy: Recycle

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wordpress
  name: nfs-volumeclaim
spec:
  accessModes:
    #- ReadWriteOnce
    #- ReadOnlyMany
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi