apiVersion: v1
kind: Secret
metadata:
  namespace: wordpress
  name: digitalocean
  namespace: kube-system
type: kubernetes.io/digitalocean-volume
data:
  token: 8d885cdc892c2fabe7354f6e5f45de90d950e37f7381b358ef01aa8f077dfdb3
  region: sgp1