# Create PersistentVolume
# change the ip of NFS server
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: wordpress
  name: wordpress-storage
  labels:
    app: wordpress
    tier: frontend
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 159.65.132.34
    # Exported path of your NFS server
    path: "/mnt/vol_master/html"
  persistentVolumeReclaimPolicy: Recycle

---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: wordpress
  name: mysql-storage
  labels:
    app: wordpress
    tier: mysql
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 159.65.132.34
    # Exported path of your NFS server
    path: "/mnt/vol_master/mysql"
  persistentVolumeReclaimPolicy: Recycle