apiVersion: v1
kind: Service
metadata:
  namespace: wordpress
  labels:
    app: wordpress
  name: wordpress
spec:
  #type: LoadBalancer
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: wordpress