---
- name: Ensure old versions of Docker are not installed. | Debian
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io
  when:
    - ansible_os_family == 'Debian'
    - (docker_versioned_pkg[docker_version | string] | search('docker-ce'))

- name: Ensure old versions of Docker are not installed. | RedHat
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-engine
    - docker-selinux
    - docker-client
    - docker-client-latest
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine-selinux
  when:
    - ansible_os_family == 'RedHat'
    - (docker_versioned_pkg[docker_version | string] | search('docker-ce'))
    - not is_atomic
